// This sketch outputs the sequence of numbers generated by a
// Linear Feedback Shift Register
//
// Roger Banks
// 2010 04 21
//

int sr[16];

void setup() {
  // put your setup code here, to run once:
  for(int i = 2; i <=5; i++) pinMode(i, OUTPUT);
}

void loop() {
  // put your main code here, to run repeatedly:
  for(byte x = 0; x < 16; x++) {
    digitalWrite(2, x & B0001);
    digitalWrite(3, x & B0010);
    digitalWrite(4, x & B0100);
    digitalWrite(5, x & B1000);
    delay(1000);
  }

}
